.Dd $Mdocdate: August 26 2021 $
.Dt SHABACK 8
.Os
.Sh NAME
.Nm shaback
.Nd SHA-checksummed backup
.Sh SYNOPSIS
.Nm shaback
.Bk -words
.Op Fl 0adDt
.Op Fl w Ar device or file
.Ek
.Sh DESCRIPTION
.Nm
receives list of files from standard input and writes the files,
including metadata in an easily repairable, linear, checksummed
to device or file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl 0
Assume NUL-terminated file list.
.It Fl a
Append to end for incremental backups. Requires seekable media.
.It Fl d
Deduplication. Write only unique data.
.It Fl D
Reduce redundancy of metadata by only writing metadata once. In
practices does not duplicate metadata after the data, but writes
the metadata only to the index at the end of the resulting
backup image.
.It Fl t
Run checksum testing for the data based on the embedded SHA1
checksums.
.It Fl w Ar device or file
Specifies the device or file that is used for writing or reading.
.Sh SEE ALSO
.Xr dump 8 ,
.Xr tar 1
